name: nseg
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python >=3.11
  - cython >=0.29 # needed as a build requirement for some dependencies that don't declare "build_requires" fields
  - numba >=0.45 # needs to be installed for elektronn3 because of LLVM dependency that pip can't handle
  - numpy >=1.24
  - boost >=1.79

  - pytorch >=2.0,<2.1
  - torchvision >=0.15
  - pytorch-cuda >=11.7 # uncomment for GPU mode
#  - cpuonly # uncomment for CPU mode

  - mongodb  # may cause mamba dep conflict
  - pymongo=3.13

  - mahotas
  - zarr >=2.15
  - h5py >=3.8
  - tensorboard >=2.12.2
  - albumentations >=1.3
  - hydra-core >=1.3
  - imageio >=2.31.1
  - ipython >=8
  - matplotlib >=3.7.1
  - omegaconf >=2.3
  - pandas >=2.0
  - pillow >=9.5
  - pyyaml >=6.0
  - scikit-image >=0.19,<0.20  # Pin due to skimage.future.graph move (TODO: Fix in lsd)
  - scikit-learn >=1.2.2
  - scipy >=1.10.1
  - seaborn >=0.12.2
  - wandb >=0.15.4
  - moviepy >=1.0.2,<2.0
  - plotly
  - zmesh
  - tqdm >=4.65
  - typing_extensions >=4.5
  - setuptools >=67.6
  - pip >=23.1
  - pip:
    - -r requirements.txt
