_name: default

source_h5_root: '/cajal/scratch/from_wholebrain/fromhd/jkor/from_lustre/new j0126 segmentation gt'
dest_flat_h5_root: '/cajal/scratch/projects/misc/mdraw/data/j0126_h5_gt_flat_numbered'
dest_zarr_flat_root: '/cajal/scratch/projects/misc/mdraw/data/j0126_gt_zarr_flat_c350'
dest_zarr_split_root: '/cajal/scratch/projects/misc/mdraw/data/j0126_gt_zarr_split_c350'

source_halfsynth_h5_origin_root: '/cajal/nvmescratch/users/riegerfr/miki_seg/'
dest_halfsynth_h5_flat_root: '/cajal/scratch/projects/misc/mdraw/data/halfsynth_h5_all_training/'
# dest_halfsynth_zarr_flat_root: '/cajal/scratch/projects/misc/mdraw/data/halfsynth_zarr_all/'
halfsynth_versions: [0, 1, 2, 3]
halfsynth_name_prefix: halfsynth_
halfsynth_use_only_training_cubes: true

raw_name: volumes/raw
gt_name: volumes/labels/neuron_ids
mask_name: volumes/labels/labels_mask
resolution: [20, 9, 9]
chunk_shape: [128, 128, 128]
include_info: true
name_prefix: j0126_gt_
zarr_zip: false
mask_shape_like_raw_shape: false
# crop_raw_shape: null
crop_raw_shape: [350, 350, 350]

dry_run: false

split_lists:
  training: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 23]
  validation: [26, 27, 28]
  testing: [0, 20, 22, 24, 25]
