# Common path prefix
path_prefix: ${oc.env:HOME}/lsdex

# Version tag
v: v1

hydra:
  run:
    # Where to write logs and config copies
    dir: ${path_prefix}/${v}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

# -> /cajal/scratch/projects/misc/mdraw/data/zebrafinch_msplit/training/
tr_root: ${path_prefix}/data/zebrafinch_msplit/training/
val_root: ${path_prefix}/data/zebrafinch_msplit/validation_n1/

enable_zarr_results: true

aff_nhood: [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]

wandb:
  ## These are directly passed to wandb.init() as **kwargs
  init_cfg:
    dir: ${path_prefix}/${v}/
    entity: mdth
    project: mlsd
    tags:
      - mtlsd
  # Visualization options
  vis:
    enable_binary_labels: true
  # Log metrics per cube with filename suffix in addition to mean metrics
  enable_per_cube_metrics: true
  # Include only files with these extensions
  code_include_fn_exts: ['.py', '.json', '.yaml', '.txt']

## Training config
training:
  # save_root: ${path_prefix}/${v}/seg_trainings/seg_trainings_${v}_tr-${tr_group}

  iterations: 100001
  # save_every: 250
  save_every: 250
  seed: 0  # TODO
  # num_workers: auto
  num_workers: 16

  # Hyperparams
  lr: 0.5e-4

  show_gt: true
  show_pred: true
  show_in_napari: false
