# Common path prefix
path_prefix: ${oc.env:HOME}/lsdex

# Version tag
v: v1

hydra:
  run:
    # Where to write logs and config copies
    dir: ${path_prefix}/${v}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

# -> /cajal/scratch/projects/misc/mdraw/data/zebrafinch_msplit/training/
tr_root: ${path_prefix}/data/zebrafinch_msplit/training/
val_root: ${path_prefix}/data/zebrafinch_msplit/validation_n1/

enable_zarr_results: false  # warning: concurrent writes possible
device: cuda

data:
  voxel_size: [20, 9, 9]

labels:
  aff:
    nhood: [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
  lsd:
    sigma: 120
    downsample: 2


model:
  num_lsds: 10
  num_affs: 3

  backbone:
    model_class: nseg.shared.get_funlib_unet
    num_fmaps: 14
    offset: [40, 40, 40]
    inp_shape: [84, 268, 268]
    ev_inp_shape: [96, 484, 484]

  # backbone:
  #   model_class: elektronn3.models.resunet.UNet
  #   num_fmaps: 14
  #   offset: [40, 40, 40]
  #   inp_shape: [84, 268, 268]
  #   ev_inp_shape: [96, 484, 484]
  #   init_kwargs:
  #     in_channels: 1
  #     out_channels: ${..num_fmaps}
  #     start_filts: 64
  #     n_blocks: 3
  #     dim: 3
  #     conv_mode: 'valid'

  # backbone:
  #   model_class: nseg.shared.get_swin_unetr_v2
  #   num_fmaps: 14
  #   inp_shape: [128, 128, 128]
  #   offset: [0, 0, 0]
  #   init_kwargs:
  #     img_size: ${..inp_shape}


wandb:
  ## These are directly passed to wandb.init() as **kwargs
  init_cfg:
    dir: ${path_prefix}/${v}/
    entity: mdth
    project: mlsd
    tags:
      - mtlsd
  # Visualization options
  vis:
    enable_binary_labels: true
  # Log metrics per cube with filename suffix in addition to mean metrics
  enable_per_cube_metrics: true
  # Include only files with these extensions
  code_include_fn_exts: ['.py', '.json', '.yaml', '.txt']

training:
  iterations: 100001
  save_every: 250
  # save_every: 2
  seed: 0  # TODO
  # num_workers: auto
  num_workers: 32
  # num_workers: 0

  # Hyperparams
  lr: 0.5e-4
  batch_size: 1

  show_gt: true
  show_pred: true
  show_in_napari: false

  save_jit: null


eval:
  raw_name: volumes/raw
  gt_name: volumes/labels/neuron_ids
  cube_root: /cajal/u/mdraw/lsdex/data/zebrafinch_msplit/validation_n1/
  # checkpoint: ${path_prefix}/${v}/train_mtlsd/2023-03-15_13-42-24/model_checkpoint_89500
  # checkpoint_path: /cajal/u/mdraw/lsdex/v1/train_mtlsd/2023-04-14_04-11-13/model_checkpoint_20000_state_dict.pth
  # checkpoint_path: /u/mdraw/lsdex/v1/train_mtlsd/2023-04-14_04-03-25/model_checkpoint_20750_state_dict.pth
  checkpoint_path: /u/mdraw/lsdex/v1/train_mtlsd/2023-04-14_04-02-04/model_checkpoint_20750_state_dict.pth
  result_zarr_root: ${path_prefix}/${v}/eval_zarr/
  threshold: 0.043
  fragment_threshold: 0.5

  write_groups:
    - raw0
    - gt_seg
    - pred_frag
    - pred_seg
